SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER customers1
AFTER UPDATE 
ON customers1
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('Data is Updated!!');
END;
/
CREATE OR REPLACE TRIGGER customers1
AFTER DELETE
ON customers1
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('Data is DELETED!!');
END;
/